//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvc_Crudoperations.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class StudentTable
    {
        public int StudentId { get; set; }
        [Required(ErrorMessage ="Name field is Required")]
        public string Name { get; set; }
        [Required(ErrorMessage = "Address field is Required")]
        public string Address { get; set; }
        [Required(ErrorMessage = "Email field is Required")]
        public string Email { get; set; }
    }
}
